// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  DeleteV1StoresByStoreData,
  DeleteV1StoresByStoreResponses,
  GetV1StoresByStoreData,
  GetV1StoresByStoreErrors,
  GetV1StoresByStoreResponses,
  GetV1StoresByStoreSparqlData,
  GetV1StoresByStoreSparqlErrors,
  GetV1StoresByStoreSparqlResponses,
  PostV1StoresByStoreData,
  PostV1StoresByStoreErrors,
  PostV1StoresByStoreResponses,
  PostV1StoresByStoreSparqlData,
  PostV1StoresByStoreSparqlErrors,
  PostV1StoresByStoreSparqlResponses,
  PutV1StoresByStoreData,
  PutV1StoresByStoreErrors,
  PutV1StoresByStoreResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Delete the store
 */
export const deleteV1StoresByStore = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1StoresByStoreData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteV1StoresByStoreResponses,
    unknown,
    ThrowOnError
  >({ url: "/v1/stores/{store}", ...options });

export const getV1StoresByStore = <ThrowOnError extends boolean = false>(
  options: Options<GetV1StoresByStoreData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetV1StoresByStoreResponses,
    GetV1StoresByStoreErrors,
    ThrowOnError
  >({ url: "/v1/stores/{store}", ...options });

/**
 * Add quads to the store
 */
export const postV1StoresByStore = <ThrowOnError extends boolean = false>(
  options: Options<PostV1StoresByStoreData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostV1StoresByStoreResponses,
    PostV1StoresByStoreErrors,
    ThrowOnError
  >({
    url: "/v1/stores/{store}",
    ...options,
    headers: {
      "Content-Type": "application/ld+json",
      ...options.headers,
    },
  });

/**
 * Overwrite the store's contents
 */
export const putV1StoresByStore = <ThrowOnError extends boolean = false>(
  options: Options<PutV1StoresByStoreData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutV1StoresByStoreResponses,
    PutV1StoresByStoreErrors,
    ThrowOnError
  >({
    url: "/v1/stores/{store}",
    ...options,
    headers: {
      "Content-Type": "application/ld+json",
      ...options.headers,
    },
  });

/**
 * Execute a SPARQL query (read-only)
 */
export const getV1StoresByStoreSparql = <ThrowOnError extends boolean = false>(
  options: Options<GetV1StoresByStoreSparqlData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetV1StoresByStoreSparqlResponses,
    GetV1StoresByStoreSparqlErrors,
    ThrowOnError
  >({ url: "/v1/stores/{store}/sparql", ...options });

/**
 * Execute a SPARQL query or update
 */
export const postV1StoresByStoreSparql = <ThrowOnError extends boolean = false>(
  options: Options<PostV1StoresByStoreSparqlData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostV1StoresByStoreSparqlResponses,
    PostV1StoresByStoreSparqlErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/v1/stores/{store}/sparql",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });
