// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://github.com" | (string & {});
};

export type V1Store = {
  id: string;
};

export type DeleteV1StoresByStoreData = {
  body?: never;
  path: {
    store: string;
  };
  query?: never;
  url: "/v1/stores/{store}";
};

export type DeleteV1StoresByStoreResponses = {
  /**
   * Store deleted
   */
  204: void;
};

export type DeleteV1StoresByStoreResponse =
  DeleteV1StoresByStoreResponses[keyof DeleteV1StoresByStoreResponses];

export type GetV1StoresByStoreData = {
  body?: never;
  path: {
    store: string;
  };
  query?: never;
  url: "/v1/stores/{store}";
};

export type GetV1StoresByStoreErrors = {
  /**
   * Store not found
   */
  404: unknown;
  /**
   * Not Acceptable
   */
  406: unknown;
};

export type GetV1StoresByStoreResponses = {
  /**
   * Get a store
   */
  200: V1Store;
};

export type GetV1StoresByStoreResponse =
  GetV1StoresByStoreResponses[keyof GetV1StoresByStoreResponses];

export type PostV1StoresByStoreData = {
  /**
   * RDF Data
   */
  body?: Blob | File;
  path: {
    store: string;
  };
  query?: never;
  url: "/v1/stores/{store}";
};

export type PostV1StoresByStoreErrors = {
  /**
   * Invalid RDF data
   */
  400: unknown;
};

export type PostV1StoresByStoreResponses = {
  /**
   * Store updated successfully
   */
  204: void;
};

export type PostV1StoresByStoreResponse =
  PostV1StoresByStoreResponses[keyof PostV1StoresByStoreResponses];

export type PutV1StoresByStoreData = {
  /**
   * RDF Data
   */
  body?: Blob | File;
  path: {
    store: string;
  };
  query?: never;
  url: "/v1/stores/{store}";
};

export type PutV1StoresByStoreErrors = {
  /**
   * Invalid RDF data
   */
  400: unknown;
  /**
   * Precondition Failed
   */
  412: unknown;
};

export type PutV1StoresByStoreResponses = {
  /**
   * Store updated successfully
   */
  204: void;
};

export type PutV1StoresByStoreResponse =
  PutV1StoresByStoreResponses[keyof PutV1StoresByStoreResponses];

export type GetV1StoresByStoreSparqlData = {
  body?: never;
  path: {
    store: string;
  };
  query: {
    /**
     * A read-only SPARQL query (SELECT, ASK, CONSTRUCT, DESCRIBE). Use this to research the graph structure, find existing entities, or check properties. DO NOT use INSERT/DELETE here.
     */
    query: string;
    "default-graph-uri"?: string | Array<string>;
    "named-graph-uri"?: string | Array<string>;
  };
  url: "/v1/stores/{store}/sparql";
};

export type GetV1StoresByStoreSparqlErrors = {
  /**
   * Bad Request
   */
  400: unknown;
};

export type GetV1StoresByStoreSparqlResponses = {
  /**
   * Query results
   */
  200: {
    head: {
      vars?: Array<string>;
    };
    boolean?: boolean;
    results?: {
      bindings: Array<{
        [key: string]: {
          type: string;
          value: string;
          "xml:lang"?: string;
          datatype?: string;
        };
      }>;
    };
  };
};

export type GetV1StoresByStoreSparqlResponse =
  GetV1StoresByStoreSparqlResponses[keyof GetV1StoresByStoreSparqlResponses];

export type PostV1StoresByStoreSparqlData = {
  /**
   * SPARQL Query or Update
   */
  body?: {
    query?: string;
    update?: string;
    "default-graph-uri"?: string | Array<string>;
    "named-graph-uri"?: string | Array<string>;
  };
  path: {
    store: string;
  };
  query?: never;
  url: "/v1/stores/{store}/sparql";
};

export type PostV1StoresByStoreSparqlErrors = {
  /**
   * Bad Request
   */
  400: unknown;
};

export type PostV1StoresByStoreSparqlResponses = {
  /**
   * Query results or Update success
   */
  200: {
    head: {
      vars?: Array<string>;
    };
    boolean?: boolean;
    results?: {
      bindings: Array<{
        [key: string]: {
          type: string;
          value: string;
          "xml:lang"?: string;
          datatype?: string;
        };
      }>;
    };
  };
  /**
   * Update successful (no content)
   */
  204: void;
};

export type PostV1StoresByStoreSparqlResponse =
  PostV1StoresByStoreSparqlResponses[keyof PostV1StoresByStoreSparqlResponses];
