// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  AddQuadsData,
  AddQuadsErrors,
  AddQuadsResponses,
  GetStoreData,
  GetStoreErrors,
  GetStoreResponses,
  RemoveStoreData,
  RemoveStoreResponses,
  SetStoreData,
  SetStoreErrors,
  SetStoreResponses,
  SparqlQueryData,
  SparqlQueryErrors,
  SparqlQueryResponses,
  SparqlUpdateData,
  SparqlUpdateErrors,
  SparqlUpdateResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Delete the store
 */
export const removeStore = <ThrowOnError extends boolean = false>(
  options: Options<RemoveStoreData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    RemoveStoreResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v1/stores/{store}",
    ...options,
  });

export const getStore = <ThrowOnError extends boolean = false>(
  options: Options<GetStoreData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStoreResponses,
    GetStoreErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v1/stores/{store}",
    ...options,
  });

/**
 * Add quads to the store
 */
export const addQuads = <ThrowOnError extends boolean = false>(
  options: Options<AddQuadsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AddQuadsResponses,
    AddQuadsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v1/stores/{store}",
    ...options,
    headers: {
      "Content-Type": "application/ld+json",
      ...options.headers,
    },
  });

/**
 * Overwrite the store's contents
 */
export const setStore = <ThrowOnError extends boolean = false>(
  options: Options<SetStoreData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    SetStoreResponses,
    SetStoreErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v1/stores/{store}",
    ...options,
    headers: {
      "Content-Type": "application/ld+json",
      ...options.headers,
    },
  });

/**
 * Execute a SPARQL query (read-only)
 */
export const sparqlQuery = <ThrowOnError extends boolean = false>(
  options: Options<SparqlQueryData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SparqlQueryResponses,
    SparqlQueryErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v1/stores/{store}/sparql",
    ...options,
  });

/**
 * Execute a SPARQL query or update
 */
export const sparqlUpdate = <ThrowOnError extends boolean = false>(
  options: Options<SparqlUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SparqlUpdateResponses,
    SparqlUpdateErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/v1/stores/{store}/sparql",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });
