// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://github.com" | (string & {});
};

export type V1Store = {
  id: string;
};

export type RemoveStoreData = {
  body?: never;
  path: {
    store: string;
  };
  query?: never;
  url: "/v1/stores/{store}";
};

export type RemoveStoreResponses = {
  /**
   * Store deleted
   */
  204: void;
};

export type RemoveStoreResponse =
  RemoveStoreResponses[keyof RemoveStoreResponses];

export type GetStoreData = {
  body?: never;
  path: {
    store: string;
  };
  query?: never;
  url: "/v1/stores/{store}";
};

export type GetStoreErrors = {
  /**
   * Store not found
   */
  404: unknown;
  /**
   * Not Acceptable
   */
  406: unknown;
};

export type GetStoreResponses = {
  /**
   * Get a store
   */
  200: V1Store;
};

export type GetStoreResponse = GetStoreResponses[keyof GetStoreResponses];

export type AddQuadsData = {
  /**
   * RDF Data
   */
  body?: Blob | File;
  path: {
    store: string;
  };
  query?: never;
  url: "/v1/stores/{store}";
};

export type AddQuadsErrors = {
  /**
   * Invalid RDF data
   */
  400: unknown;
};

export type AddQuadsResponses = {
  /**
   * Store updated successfully
   */
  204: void;
};

export type AddQuadsResponse = AddQuadsResponses[keyof AddQuadsResponses];

export type SetStoreData = {
  /**
   * RDF Data
   */
  body?: Blob | File;
  path: {
    store: string;
  };
  query?: never;
  url: "/v1/stores/{store}";
};

export type SetStoreErrors = {
  /**
   * Invalid RDF data
   */
  400: unknown;
  /**
   * Precondition Failed
   */
  412: unknown;
};

export type SetStoreResponses = {
  /**
   * Store updated successfully
   */
  204: void;
};

export type SetStoreResponse = SetStoreResponses[keyof SetStoreResponses];

export type SparqlQueryData = {
  body?: never;
  path: {
    store: string;
  };
  query: {
    /**
     * A read-only SPARQL query (SELECT, ASK, CONSTRUCT, DESCRIBE). Use this to research the graph structure, find existing entities, or check properties. DO NOT use INSERT/DELETE here.
     */
    query: string;
    "default-graph-uri"?: string | Array<string>;
    "named-graph-uri"?: string | Array<string>;
  };
  url: "/v1/stores/{store}/sparql";
};

export type SparqlQueryErrors = {
  /**
   * Bad Request
   */
  400: unknown;
};

export type SparqlQueryResponses = {
  /**
   * Query results
   */
  200: {
    head: {
      vars?: Array<string>;
    };
    boolean?: boolean;
    results?: {
      bindings: Array<{
        [key: string]: {
          type: string;
          value: string;
          "xml:lang"?: string;
          datatype?: string;
        };
      }>;
    };
  };
};

export type SparqlQueryResponse =
  SparqlQueryResponses[keyof SparqlQueryResponses];

export type SparqlUpdateData = {
  /**
   * SPARQL Query or Update
   */
  body?: {
    query?: string;
    update?: string;
    "default-graph-uri"?: string | Array<string>;
    "named-graph-uri"?: string | Array<string>;
  };
  path: {
    store: string;
  };
  query?: never;
  url: "/v1/stores/{store}/sparql";
};

export type SparqlUpdateErrors = {
  /**
   * Bad Request
   */
  400: unknown;
};

export type SparqlUpdateResponses = {
  /**
   * Query results or Update success
   */
  200: {
    head: {
      vars?: Array<string>;
    };
    boolean?: boolean;
    results?: {
      bindings: Array<{
        [key: string]: {
          type: string;
          value: string;
          "xml:lang"?: string;
          datatype?: string;
        };
      }>;
    };
  };
  /**
   * Update successful (no content)
   */
  204: void;
};

export type SparqlUpdateResponse =
  SparqlUpdateResponses[keyof SparqlUpdateResponses];
